// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }: LayoutProps<"/">) {
// //   return (
// //     <html
// //       lang="en"
// //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// //     >
// //       <body className="min-h-full flex flex-col">{children}</body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import { Inter, Barlow_Condensed } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
// import FloatingCall from "@/components/FloatingCall";
// import { site } from "@/lib/site";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
//   display: "swap",
// });
// const barlow = Barlow_Condensed({
//   subsets: ["latin"],
//   weight: ["500", "600", "700"],
//   variable: "--font-display",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   metadataBase: new URL("https://msalshamsi.ae"),
//   title: {
//     default: `${site.legalName} | Crane Rental & Heavy Transport in Abu Dhabi`,
//     template: `%s | ${site.shortName}`,
//   },
//   description:
//     "Abu Dhabi based crane rental, heavy equipment transport, vehicle recovery and general transport company operating since 2007. Oil field and military works experience. Available 24/7.",
//   keywords: [
//     "crane rental Abu Dhabi",
//     "mobile crane hire UAE",
//     "heavy equipment transport Abu Dhabi",
//     "vehicle recovery Abu Dhabi",
//     "towing Musaffah",
//     "lowbed trailer rental UAE",
//     "general transport Abu Dhabi",
//   ],
//   openGraph: {
//     title: `${site.legalName}`,
//     description:
//       "We lift so you can build. Crane rental, heavy transport and recovery in Abu Dhabi since 2007.",
//     type: "website",
//     locale: "en_AE",
//     siteName: site.shortName,
//   },
//   robots: { index: true, follow: true },
// };

// const jsonLd = {
//   "@context": "https://schema.org",
//   "@type": "LocalBusiness",
//   name: site.legalName,
//   alternateName: site.arabicName,
//   slogan: site.tagline,
//   foundingDate: String(site.established),
//   telephone: [site.phonePrimary, site.phoneSecondary],
//   email: site.email,
//   address: {
//     "@type": "PostalAddress",
//     streetAddress: site.address.line1,
//     addressLocality: site.address.city,
//     addressCountry: "AE",
//   },
//   openingHours: "Mo-Su 00:00-23:59",
//   areaServed: "United Arab Emirates",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={`${inter.variable} ${barlow.variable}`}>
//       <body className="flex min-h-screen flex-col">
//         <script
//           type="application/ld+json"
//           dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
//         />
//         <Header />
//         <main className="flex-1">{children}</main>
//         <Footer />
//         <FloatingCall />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FloatingCall from "@/components/FloatingCall";
import { site } from "@/lib/site";
import CrispChat from "@/components/CrispChat";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});
const barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://msalshamsi.ae"),
  title: {
    default: `${site.legalName} | Crane Rental & Heavy Transport in Abu Dhabi`,
    template: `%s | ${site.shortName}`,
  },
  description:
    "Abu Dhabi based crane rental, heavy equipment transport, vehicle recovery and general transport company operating since 2007. Oil field and military works experience. Available 24/7.",
  keywords: [
    "crane rental Abu Dhabi",
    "mobile crane hire UAE",
    "heavy equipment transport Abu Dhabi",
    "vehicle recovery Abu Dhabi",
    "towing Musaffah",
    "lowbed trailer rental UAE",
    "general transport Abu Dhabi",
  ],
  openGraph: {
    title: `${site.legalName}`,
    description:
      "We lift so you can build. Crane rental, heavy transport and recovery in Abu Dhabi since 2007.",
    type: "website",
    locale: "en_AE",
    siteName: site.shortName,
  },
  robots: { index: true, follow: true },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  name: site.legalName,
  alternateName: site.arabicName,
  slogan: site.tagline,
  foundingDate: String(site.established),
  telephone: [site.phonePrimary, site.phoneSecondary],
  email: site.email,
  address: {
    "@type": "PostalAddress",
    streetAddress: site.address.line1,
    addressLocality: site.address.city,
    addressCountry: "AE",
  },
  openingHours: "Mo-Su 00:00-23:59",
  areaServed: "United Arab Emirates",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${barlow.variable}`}>
      <body className="flex min-h-screen flex-col" suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <CrispChat />
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <FloatingCall />
      </body>
    </html>
  );
}
